/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.firebase;

import org.appcelerator.kroll.KrollProxy;

import org.appcelerator.kroll.annotations.Kroll;
import com.google.firebase.storage.*;

@Kroll.proxy(creatableInModule = FirebaseModule.class)
public class FirebasestorageProxy extends KrollProxy {
	FirebaseStorage storage;

	public FirebasestorageProxy() {
		super();
		storage = FirebaseStorage.getInstance();
	}

}