/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.firebase;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiContext.OnLifecycleEvent;

import android.app.Activity;
import android.os.Bundle;
import android.support.annotation.NonNull;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthCredential;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.auth.GithubAuthProvider;

@Kroll.proxy(creatableInModule = TifirebaseModule.class)
public class AuthenticationProxy extends KrollProxy implements OnLifecycleEvent {
	private final class OnCompleteHandler implements
			OnCompleteListener<AuthResult> {
		@Override
		public void onComplete(@NonNull Task<AuthResult> task) {
			if (task.isSuccessful()) {
			} else {
			}
		}
	}

	KrollProxy proxy;
	private FirebaseAuth auth;
	private Activity activity;
	private FirebaseAuth.AuthStateListener authListener;
	private static final String LCAT = "FiBaProx 🚝🚝";

	public AuthenticationProxy(KrollProxy proxy) {
		super();
		this.proxy = proxy;

	}

	@Kroll.method
	public void signInAnonymously() {
		auth.signInAnonymously().addOnCompleteListener(activity,
				new OnCompleteHandler());
	}

	@Kroll.method
	public void createUserWithEmailAndPassword(String email, String password) {
		auth.createUserWithEmailAndPassword(email, password)
				.addOnCompleteListener(activity, new OnCompleteHandler());

	}

	@Kroll.method
	public void signInWithEmailAndPassword(String email, String password) {
		auth.signInWithEmailAndPassword(email, password).addOnCompleteListener(
				activity, new OnCompleteHandler());
	}

	@Kroll.method
	public void signInGithub(String token) {
		AuthCredential credential = GithubAuthProvider.getCredential(token);
		auth.signInWithCredential(credential).addOnCompleteListener(activity,
				new OnCompleteHandler());
	}

	@Override
	public void onCreate(Activity activity, Bundle savedInstanceState) {
		this.activity = activity;
		auth = FirebaseAuth.getInstance();
		authListener = new FirebaseAuth.AuthStateListener() {
			@Override
			public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
				FirebaseUser user = firebaseAuth.getCurrentUser();
				if (proxy.hasListeners("onAuthStateChanged"))
					if (user != null) {
						KrollDict result = new KrollDict();
						result.put("displayName", user.getDisplayName());
						result.put("uid", user.getUid());
						result.put("email", user.getEmail());
						result.put("photoUrl", user.getPhotoUrl());
						proxy.fireEvent("onAuthStateChanged", result);
						// User is signed in
					} else {
						// User is signed out
					}
			}
		};
	}

	@Override
	public void onStart(Activity activity) {
		super.onStart(activity);
		auth.addAuthStateListener(authListener);
	}

	@Override
	public void onStop(Activity activity) {
		if (authListener != null) {
			auth.removeAuthStateListener(authListener);
		}
		super.onStop(activity);
	}
}