/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.firebase;

import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.android.gms.common.*;
import com.google.android.gms.common.api.*;

// This proxy can be created by calling Tifirebase.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = TifirebaseModule.class)
public class DatabaseProxy extends KrollProxy {
	FirebaseDatabase database;
	private static final String LCAT = "FiBaProx";

	public DatabaseProxy() {
		super();
		this.database = FirebaseDatabase.getInstance();
	}

	@Kroll.method
	public DatabaseReferenceProxy createReference(String ref) {
		return DatabaseReferenceProxy.createReference(this, ref);
	}

}