/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.firebase;

import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

// This proxy can be created by calling Tifirebase.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = TifirebaseModule.class)
public class FirebasedatabaseProxy extends KrollProxy {
	FirebaseDatabase database;
	private static final String LCAT = "FiBaProx";

	public FirebasedatabaseProxy() {
		super();
		database = FirebaseDatabase.getInstance();
	}

	@Kroll.method
	public void setValue(String _ref, String _value) {
		DatabaseReference ref = database.getReference(_ref);
		if (ref != null && _value != null) {
			ref.setValue(_value);
		}
	}

}