/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.firebase;

import EventProxy;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.android.gms.common.*;
import com.google.android.gms.common.api.*;

// This proxy can be created by calling Tifirebase.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = TifirebaseModule.class)
public class ReferenceProxy extends KrollProxy {
	FirebaseDatabase database;
	DatabaseReference reference;
	private static final String LCAT = "FiBaProx";

	public ReferenceProxy() {

		super();

	}

	public static ReferenceProxy createReference(DatabaseProxy databaseProxy,
			String refString) {
		databaseProxy.database.getReference(refString);
	}

	@Kroll.method
	public void setValue(String _ref, String _value) {
		DatabaseReference ref = database.getReference(_ref);
		if (ref != null && _value != null) {
			ref.endAt(true);
			ref.setValue(_value);
		}
	}

}